# Generated by Django 3.1.7 on 2021-02-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('invitation_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.invitationstatus')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='guests',
            field=models.ManyToManyField(to='app.Guest'),
        ),
    ]
