# Generated by Django 3.1.7 on 2021-02-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210224_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='invitation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invitationstatus'),
        ),
    ]
